version: "3.9"

services:
  backend:
    build:
      context: ./transport-app-backend
    ports:
      - "8081:8080"  # A porta do container 8080 é mapeada para a porta 8081 no host
    env_file:
      - ./transport-app-backend/.env
    volumes:
      - ./transport-app-backend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    networks:
      - transport-network

  frontend:
    build:
      context: ./transport-app-frontend
    ports:
      - "80:80"  # Porta 80 do host mapeada para a porta 80 do container
    environment:
      - PORT=80
    volumes:
      - ./transport-app-frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    networks:
      - transport-network

networks:
  transport-network:
    driver: bridge
